### ISSUE TITLE
Will it work for Galaxy A52

### ISSUE THREAD

**Issue by HamzehTamimi** [map220v/postmarket_samsung_a72q#1]
Will it work for Galaxy A52 since they have almost the same specs?

**Comment by map220v** [comment]
Yes it works(with a52q firmware files). But seem to have issues with starting MPSS.
https://github.com/leandrofriedrich/postmarket_samsung_a52q
https://wiki.postmarketos.org/wiki/Samsung_Galaxy_A52_4G_(samsung-a52q)
