### ISSUE TITLE
Stuck at Download mode with black screen!

### ISSUE THREAD

**Issue by elvaalxv** [map220v/postmarket_samsung_a72q#2]
pmbootstrap is worked. But heimdall flash is failed. Try to flash manually with TWRP, but phone boot to Download mode with black screen and OEM LOCK: ON (U)
My phone bootloader is unlocked and running PE ROM.

**Comment by elvaalxv** [comment]
[last_kmsg.txt](https://github.com/map220v/postmarket_samsung_a72q/files/9179685/last_kmsg.txt)

**Comment by map220v** [comment]
Backup stock dtbo and flash [emptyDTBO.zip](https://github.com/map220v/postmarket_samsung_a72q/files/9179817/emptyDTBO.zip) to boot mainline kernel

**Comment by elvaalxv** [comment]
It booted
